# Upload and publish this package to https://hackage.haskell.org/
name: Hackage Publish
on:
  # https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  #
  # “When a workflow is configured to run on the workflow_dispatch event,
  # you can run the workflow using the Actions tab on GitHub”
  #
  # “To trigger the workflow_dispatch event, your workflow must be in the
  # default branch”
  #
  workflow_dispatch:
jobs:
  hackage-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: haskell/actions/setup@v2.4.0
        # https://github.com/haskell/actions
        id: setup-haskell-cabal
        with:
          ghc-version: "9.4.5"
          cabal-version: "3.10"
      - run: cabal v2-haddock --builddir=dist-newstyle/docs --haddock-for-hackage
      - run: cabal v2-sdist
      - uses: haskell-actions/hackage-publish@v1.1
        # https://github.com/haskell-actions/hackage-publish
        with:
          hackageToken: ${{ secrets.HACKAGE_AUTHTOKEN_001 }}
          packagesPath: dist-newstyle/sdist
          docsPath: dist-newstyle/docs
          publish: true # Publish directly instead of uploading a Candidate

# cabal Support authentication tokens for uploading files
# https://github.com/haskell/cabal/issues/6738
